version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword      # root user password
      MYSQL_DATABASE: my_database            # database name
      MYSQL_USER: my_user                    # new user
      MYSQL_PASSWORD: my_password            # new user password
    ports:
      - "3306:3306"                           # expose MySQL to host
    volumes:
      - mysql-data:/var/lib/mysql             # persist database data

volumes:
  mysql-data:
